#!/usr/bin/env ruby
# frozen_string_literal: true

# Load the command from the gem
require_relative '../_plugins/create_example_lesson_command'

# Run the command
options = {}
Jekyll::Commands::CreateExampleLesson.process(options)

